using System;
using System.Collections.Generic;
using System.Text;

namespace SystemFramework
{
    public class PYWBCode
    {
        public PYWBCode()
        { 
        }


        //-------------------------------生成拼音码以及五笔码--------------------------------------------
        /// <summary>
        /// 返回五笔码
        /// </summary>
        /// <param name="inputstring"></param>
        /// <returns></returns>
        public static string GetWBCode(string inputstring)
        {
            string thisletter = inputstring.Trim();
            int letterlen = thisletter.Length;
            string pystring = "";

            string LETTER1 = "ghgdgvatuggunnenkouftgqxnttrtnnmxgtucnladqturugivfryifeqfeofhqg ffmdgcgyyyyyyyuyywwnwwwwwwwwwwwhwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwgwwwwwwwwwwwwwwwww                                                               wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww wwwwwwwwwfwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww                                                               wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwgwwwwwwwwwwwwwwwwwww wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwabwwtdhvaufdffftuffitmgwugwwummmdmmmmjmajppppppppppppduuuuuuuuuuuuuuuuuuuuuu                                                               uuuuuuthntmmmmmmmmubbvvttfrefnvxevnwckffmggffebfgggyhkwfquftdaa ugmxcygwydgymnmtwamwxugnfmcacvtlyhqwkhwwiywwrwtyxnlrylrrdriurufucafgfgttgycfuyfusxdtjcakweonsfgxvrqattuuhyatthdtyaqqqqqqqqqqqqq                                               ";
            LETTER1 = LETTER1 + "                tqqtxaaaaaaaaaaaaaaaaaaaaaaaaaanavflnnfeaxghhmqavqtwgwkswqdddrd dddddddddddddddddddddddidddcvdccngcccffnntcfcnpfnhokvkbkkykkkkkkkknkdkkkkkkktkkekikkkkktkkkkkkkkkkkkkkkkxkkkkkkkukkkkkkk kkkkkk                                                               kkkkkkkkkkmkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkdkkgkkfkkk kkkkkkkkkkkkkkkkukkkktukkyykkhkkkkyrkdkkkkkkkkkkkkkkfkkkkkkkdkkkkkkkkkkkkkfktkkkkkkigkkkfkkkkfkkkkkkkkkkkkkeklkfkkkkkgkkkkkkkkk                                                               kkkkkkkkkkkkikkkkkkkkkkkkkkkkkkkkkkkkkkkkkdkkkkkkkkkkkekkkkkykk kkkkkkkkkkkukkkkfkkkkkkkkkkkkkkkkkkkkkkkkkkkfkkkgkkkkkkkkkfxkkyqkkkkkkkkkkkkkkkukkkkjkfkakkkkkkmlllllllltlllllllllllllcllllllll                                                               llllllllllllffffffdftfffdffjffffffffffxfirffgfifjffffffffffffff ffwfffffufsrffffffffffffffffffffffftifftffbffffmfffrffffsffffffffffffffffffffffbifyfaffgffsffffffffffffffcffffffffffvfffffffiyf                               ";
            LETTER1 = LETTER1 + "                                ffflfffffvffofffffffifffffafffifbfffffffiyfffyffflyffffffffffff vfnffffffffbfffffffffyfbfbnfffffffffffffeffnfswffffffiffgfdffflffffffufhffffflfffnfffffffffffffjetttytcfwqodqqqvqqqqayanndddddd                                                               dddgdddyhuqddcddddddgdctudddndddlxdvvvvvvvnvvvvvvvvvvvvbvnjvvvv vvvvvvqvvvvvvvlvvvvvvwvvvvvvhvvvvvvvvvvvvvvlvvvvvvgvvvvvvvvvvvvvrvvvvvvvvvvvvvvnvvvvvvvvvvvvvvvvvvvbkvvvvvvvvvvvvvvdvvvvvvavvvv                                                               vvvvvvvvvvvgvxvvvvvvvvvvvvvvvvvvvvvvvvavvvvvvvvvtvvvvvvvvvvvvvv evvvvvvvvvtvvvvvvvvvovvvvvvgvvvvvavvvfvvvvvvvvgvvuvvvvvvvvvvvvvvvdvvvvvavvvvvvvvvvvvvvvuvvvvvvvvvvvvvvvvvdvhivvvvvvvvvvvfvvvvvv                                                               vvvvxvvvbbbnbxbbbbabbyfrnbbbxppppppppppppppppppppppjppppppppppp ppppppppppppppppppppppppppppeyaggfngvfouiwthiidjaiwwdwvgfvvvvvvgvnnnnnncnrnnnnnnnnnnnnnnnnnuttmmmmmmmmmbmmmmmmcmmmmmmmmmmmmmmmm               ";
            LETTER1 = LETTER1 + "                                                mmmmmmmmmmmmmmimmmmmwmmmmmmmmmmmmmmmmmmmmmmmmmmmqmmmmqmmwmmmimm mmmpmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmtmmcmmmmkmmmmmmmmwmmmmmommmmmmmmmmmmmmmmmmmmmmmmmmgmmmmmmmmmmmmmmmmmmmmmmbmm                                                               mmmmmmmwmmmmmmmmmmmtmmmmmmmmmmmmmmmmmmmmmmmmmmxmmmmmmmmvygevaaa grvabnuchtmnmmqymwmmmyvmmuvwmmmwvgjmmmmammmmmmmmfmmmtmmmetmmmmmmdmmmmuumnmmmmfmmmmmmgufxyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy                                                               yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyvmrlslwfwnaaagqxxxuxxxxxxx xxxuxxxxxxxxxxxpxoxxxuxxxxxxxxxnxxnvxvvvyyagmpsgttttttttttttttttttttttttttttttttttttqtttttttttrtnfnntnvnnnyyngnrnntnnnnnnnnnnnn                                                               nnnnnnnndmnnxrwnnnnqnnnnfswnvnnnnnnnnnnnvnnntnnnnnbnnbnnnnygwnn nnnwnnrnnnqnnnnannntntynngnnfnunpnnnnnsnnhnnipnanntnnjnnnngnrnvfnnndnnnnnnfnnnnnnnnnnnnncnpenvnnnnfnnunnnnnnlnnnnsnnbnnnnlinnn";
            LETTER1 = LETTER1 + "n                                                               wncnnannnngnlnntnnnnnfnfnntnghnnnnnyafnndnwunnddttntnnwqnnnunnn ssnfnnnnndnnnnonnnnnnnnpnnnnnnnnannnnannneynnnnnndqninnnnnnonnninnnnnnnynngnntnnnnennnnnnxannnuuqaamamduwiwsgdphkhhhygyyynyyyyy                                                               rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrfrrrrrrrrrrrrrrr rrvrrrrrrrrrrfrrrrrrrrrrrrrrrvrrrrrrirrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrarrrrrrrrrrrrrrrrrrrrrrr                                                               rrrdrrrrrrrrrrrrrrrrrrrrrgrtrrrrirrrrrrrrrrrrrrrrrrrrrrrrrrrrrr rrrrtrrrrrrrrrrrwrrrrrrrrrrrrrrrrrrrrrrrrrfrrrrrrrrgffrrrrrrrrrrrrfrluryrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrlrrrrrrrrrr                                                               rrrrrrrawrrdrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr rxrrrrrrrrfudfgnfwrhqncwghtwfdwugmwuwmcjjoduicjtnmmubkhaqftutllwufwwyyyyyyyyyyqckvfalrnqlafvaoqrxnyyyyyyyygyyy";
            LETTER1 = LETTER1 + "yyyyyyyyyyyyarmjj                                                               jjjjjmjjjgjjjjjjjgjjjjjjjdjjjjjjjjjjjnjjjjjjjjjjjjjjjjjjgjjjjjj jjjvjjrjjjjjjjjjjsyjjjjjjjjjjjljjnjjjjjcjjjjjjujjjjjjjjdjjlfjjjjjjjjjjjjujjjrjjjjdjjjjjjjjjjjjkjjjjjjjjjjjjjjjjjxjjjjjjqvfjuajw                                                               jfuweeemeeeelyeaeeaeeeegfsssessssssgssssssssssynssssssssssssgss sssfswssssxssssssssssssssssssssscspssafsssssssfsswsspssssssssssssssssssssssssssssigsfsdsssssstswsssussssssssssssssssvsssfssssss                                                               sssssissssssssssssssssssssssssssssssssssssspwstsssspssssssssshs sssssssstyssssasssdssssgssssswssssssysssssssssssbassssssssssywsssssssssssswfssssssssssswsssssssssssssssssswssssssssssssssscssss                                                               sssssssssossssssussussssssssssssssfsssrssssssssjsssossssssssess ssystsssssssssksssfssssssssssssslswsssssssnsssfssssfsssxsssssssssssssssssswsssssssssssssssssss";
            LETTER1 = LETTER1 + "ssssssssssssssssrssssssssssssssss                                                               dssssssnsssssssssssssssssssssssssbssssssssssssslswsssssssssssss ssssssssssssssssssssodsssssssssssssssslsssssssssssgssssssssssssssgsssssbsssssssssssbssssssssswssssssssssxsssssssswssssjwqvbrylu                                                               ftwhyxgcocqqsammswyrtaaahuthffvouwllfwcahhhhhhhvhhhdhhdwhgggggg gggggggggggggggggggggggggggggggyfaqffqfvylavqafxtfxlqttxiltnwtbttttgrttcttjttdjjcktfucyktatlqrrrrrrrrrrrrcyniiiiiiiiiiiiiiiiimi                                                               iiiiiiiifiiiiiiiiiiiiiiipiiiiiiigiiiiiiiiiiiiiiiiiisiiiiiiiiiii iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiitiiiiiiiiiiiidiiiiiiiiiiieiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii                                                               iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiwiiiiiiiiiiiiiiiiiidiiiiiiiiiiiii iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiitiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii";
            LETTER1 = LETTER1 + "eiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiioiiiiiiiiiiiiiiii                                                               iiiiiiiiiiiiiifiiiiiiiiiiifiiiiiiiiiiiiiiiifiiiiiiiiiiiiiiinixi iiiiiiiiieiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiieiiiiiiiiiiiiiiiiiiiiiiiiiiiiwiiiiiiiiiiiiiiiiiiiiiiiiiiiitiiiiiiiiiiiiiiiiiiii                                                               iiijiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiit iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiixiiiiiiiiiiiiiiiiriiiiioooqoooofvaowoooooooooooaojooooooooooooooqoooonooooooqwoogtooooodfoo                                                               obooooooogooroooooooooookwovoooynoorboooouoooootobyoooooooooooo oojoooojooooooooooooooofoooaoooojhooooooooooovooooooooooooooocoootocoooooooooooooooooooootooodooofxoooooooooooootfoooooooosooos                                                               oooionoowoowoooooooooooooooooyooooofooohoooaooooooooooqoooooooo ooooooyooooooeereeelwqgnnnnnnhttttttttttttirrrrrrrrrrrrrrrurrr";
            LETTER1 = LETTER1 + "rytrrrrrrrfrrrrroryrnfrrrrrrrrrrrwtrwdqqqqqqqqqqnwqqqhqqqqqqqqqqq                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       ";
            LETTER1 = LETTER1 + "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ";
            LETTER1 = LETTER1 + "                                                                                                                                                                                                                                                                                                                                                                                                                              qqqqqqqqqqqqqqqqqqqqqdqqqdsqqqqjqqqqqqqqqqqqqqqqqqqqqqqqqmqqqqq qqqqnqqqqqquqqqqqqqqqiqqqqqqqqqqq                                                                                                                                                             qqqqqqkqqhqqqqqqqyyyggtggggggggggggggggggghaggggggggggggggggggg ggggggggggggggggggggggggggggggggg                                                                                                                                                             gggggggggggggggggggggggggggggjggggggggggggggggggggggggggggggggg gggggggggggggg";
            LETTER1 = LETTER1 + "gggggoggigggggfgggg                                                                                                                                                             gggaggggggggggggggggigggggggggggggggggggggggggggggggggggggggggg ggggggggggggxggggggrrfrgagqwypgqg                                                                                                                                                             dcqkdqgittcytguotukuagotqyhhahijtyuggttqjtmlllrljeyhlllgoyillyl yflrllwllolvwllllglvilgllllvlllll                                                                                                                                                             gjlgncfuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu uuuuuuuuuuuuuuuuuuuuuyuuuuuuuuuuu                                                                                                                                                             uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuwwwqwrrrrrrrrrrrrrfrrr";
            LETTER1 = LETTER1 + "r rrrrrrrrrrrrrrrrrhhfasfuhqhfyfhegkbfrkkyruatadebarpwrjmepejmmggrpwtniarrkktwucrkardfflwrsdrwmrtggrrtwstrrwuulxddssexsdjqwyaeqyv                                                               xdtdqiigfivaxvlatwhdfiwaxhhhhhhhhhhhhhhhhhhhhhhlhhhdhhhxhhhhhhh hhhhhhhhhhlhwhhhhhhhhhhhhhhhhhlhhafwwqprrjeqosddrudumqwqttopdastmxgdkugtxkttgaaxxxtyuuuunnnnnbalxmywyyuuuysheguukusyiiprrusgtqo                                                               thhhhhhlhhnhhhhhhhghhhhhrhhhhfhhlhehhahhhhhhbhhhhhhhhhhhhhhhhhh hhghhhhhhhhhhhhhhhhhhhxhhhhcccccxuugarrqiffrqtwrteeiicrhkpfidhtunrqfsfmhkeeaahcggnnoatwiarosgadtwminkrcaasdrpwuyrherrjqyxquuyjq                                                               qttttttddddddkddddddddddddddddddddkddvdddddddddddddddddddddkddd dddddddddddddrdidddddddddaddddaddfiitwedijkwfrqfkivkolrrrtisadijnibfprtfsdktttiybkctkurjinxcbhwnffroyujmprslktttwxhntpbsdkqqibs                                                               ddidddddddddddkdddkdddddddddkddddddddddddddddd";
            LETTER1 = LETTER1 + "ddddkdddldddkdddd ddddddddddddddddddddddddddddddgdddwfrqtrkpswtkkupmyuwkorqtdssdixdnxuadhtuuyhgmubatqwwuostwktprmweuoinsdfdrrrrqrdturdkgwfggwwwtv                                                               dddwdddnddddddwdddddddddldddsddddudddddddppppppppppppppppppfphp pppppppppppppppppppppppppppppppppcbrmuurejrwniyxniriasvrkwqpngtnuuttrkowthwcfwimttqinvryfatuuuxfridhmgrjwqynuindkmunrkqykwdjryc                                                               ppppppppoppppppppptpppppppppppppppmhtttttttottttttttttttttttttt tttttttuttttttyttttttttttttttttttshkqshqpytatanfswnuiqrubggufhgtqyfhmsqeyivutqwoxfubcfkkyglqrrrkqdftmktmnbjmtwpyvgdrjkqldqbqqif                                                               tyttttttttttttttttttttttyfttttttytttqtxtttttttttttttttttttttttt ttttttttttpppppppppppppppppppppppavltwtuigamttsdqtmorramqqifayeybvwyxyadkneaykeyixaskrwxfsiodwwnodfsjmqmuotuxydmwgfgeqrrlmrtwwe                                                               pppppppppppppppppppppppppppppp";
            LETTER1 = LETTER1 + "pppuuuuuuuuuuuuuuuuuuuruuauuuuuuu uuuuuttttttttttttttttttttttttttttiippxgrlwwweeyyfgsmtwwwweqpybvxkkkynsquifasstefdtnummqrexmistryyuorqttssraweupaasjubqwtxskdgyu                                                               ttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt ttttttttttttttttttttttqttttttttttfbsaaaadwtwpxaaraaqqiaqfsmqdaktwibvfdjmweddlytrkprptrnsuppctqrnixiyqgffdjqulrywsskkwlisqyljyfk                                                               tttttttttttttttttttttttttttttttttttttttttttttttttt tttttttttttt tttttttttttttttttttttttttttttttttmbirypcsnafwipbkpfrrjnnoiidstfkyyfvdkikkaasttwwweuiifpplklutqnkystnlkojiipxxkwqkdwrktqgfadjqoi                                                               tttttttttttttttttttttttttttttttttttttttttttttttooooojooooqooooo oxooooooooooovoooooooooooootoooooxhkrgiyakwqigawystnifcgsgxrkkuuoipxanadjtrmnojmnydritnjlvndfgjmtwoiyyxaqvfiipiwoaaafwpffaslttt                                                               ooooooooooooof";
            LETTER1 = LETTER1 + "oooooioooooooonoooooboowaboxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxrxxxxxxsxxxxxxxeqyiycvxxfsgltwequivvxrminarutwwynippyyvnbvxxfsgwplagslqwtwllvgjjituuuycvxasgddrrtwuuasjkmmqtw                                                               xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxwdxxxxxxxxxxxxxxcxuxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxdxxxxwtwqiiivwuuuixauuyaubasdweuuicvkrqtweqqqxxvfsllkprrxttbffassrhuixqvaaalwwuynmtrqwipjqwyfagsroi                                                               xxxxxxxxxxxvxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxaxxxxxtxxxxxxxxx xxrxxxxxxxxxxxxxxxxxxxxxxyxxxxxxxncadahjqynooxfajcgfaqtuuuuuoprpxgdqqvidfhvvtyuarquncanktiibrrahkkqwqnonrkvwuuxrrrrweiuyxfaqpvm                                                               xxxxxxxxxxxxxoxxxxxxtxxxxxxxxxxxxxxxxfxeexxxxxxxxxxxxxxxxxxfxxx xxxxxxxxaxxxxxlxxxxxxxxxxxxxxxgxxwuivckkhkgrsmnffafdrynorryofrotfassdjtfksidypyhkvvfkpabrrkrpskpasypdfrkeftwnpfatqsdhjufdmpadrw                                                             ";
            LETTER1 = LETTER1 + "  xxnxxxtxxxxxxlxaxxxxxxnxxxxxxxxxxxxxxxxxoxxxxxlxxxxxxxxxxxxxxxx xxxxxxxxxxxrrrrrrrrrorrrrlyhlrrlmqnifjrlrryufrkjeukaggassrtuuiyrjnxoigsqyyyirapfwvsoiaqfqadlwcreoissudttttqyigsjqpaagsgddddtwww                                                               lplllllllllllllllllllllllllmllllllllgduguuuuuueuuuuuvuuuiuuuuuu uuuuuuunnndnnnjsvnnnnnfwqmvwnpnmnuuoivlgkwbalqynipweqyoxouiiygljjyyrbwuopbibrqyogggiqgsdfjwqiuwyrgafhqwuuvbmwkwigsdqqyuisuddktp                                                               kpnnnnnnsnnroffwhlffffffddmdddgddddddddddddbbbbbbbbbbbbbbbbabbb bbbbutbbbbbbbbbbbbbbbftbbbbbbbinbbdrbsortibahhyorhhqsdfkmyipvbnckqwynnxhrtyixyyyiqtrlrlwwixyajllqtcpaicxvygdjckkkfngfdehqyiajni                                                               uygvyeepweeeeeekeeeeeeeeeeeehedeemeeeeeeheeeeeeeeeqeefebmeeleev eeeeeeeeeeedeeemeweeeeeeeeeeeeeeeyaayynaqaqtcqqajmeqtgsssfoinvqtujpvvuuwaasjqqsbhsyyoyxoteipppshxjqqvxdarhatiyvagnrltnujjkqqwyr                                             ";
            LETTER1 = LETTER1 + "                  eeeeeeeeeaeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeoeeeyeeeeeeeheeeeeef meeeeeeeeeeeeeeeeeeeeeeeendeeeeedaaseyyyrgalliipbycartyvxaaaaashhttwkkqvvxrevddflcgrenuikqmvcvfwinrwaeuiarrdrrwvsqnrbakqqiwsqup                                                               eeweeeeeeyeexaeaananttwtttggfggfqtvwwwawwttttwwwttntttttttttttt tttttttttttttttttttttttttttttttttrirrqxeipgvvvvjhurnoykaaaakwikkrmngrrttiisitthluuryuderkqopkikefdmbswikwdryifasdteeerdfdfrrngl                                                               ttttaumbnaaaaaaaaaaaamaaaaaaaaaaaaaqaaaaaaaaaaaaaaaaaaaaaaataaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabakeuhauwnntwtcsissrurhwkbrfaagwuynfihidrrourqwaaaafsluiyjiaasdgauiiiasdhlmeyyppcfmtwyddkrtyiiyr                                                               aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaahaaaaaaaaaaaaaaaaaanidrqqtttwyflqquikiylmquskeufaxrsqynshtwaaramwpaaenpqwudgaarwpiglrwqiajrnxyygptrrgfluifajmtnci                             ";
            LETTER1 = LETTER1 + "                                  aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbhfflassrwuuducroufasdipvqomiyfrkyqrxartwwvfwyvvxrwjaaaagoipxprcmajwbvdeitplbagquiaxriaeqppdc                                                               aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaawackfrcrvgqiswadqqixwkqtjgasmmopubrmeuiyxfwuijhiisrtoaquikvxdmjtwfrtnipydjkwtivxpipvajnifttttx                                                               aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaagaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaidtecjrqyiynnfdrjwwqpyktwncvaffasgrrrrjkktwwtqqynppynrupdrweuuassgrlhwinnmyyajjlltvnsssgdjjyoi                                                               aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaavndryejsrfcdyihtkhkeyduoarkltnxgdfklwwqnswwwupyyrtrkaswggswuipyvsatkbbxmdmtubbbrtaskxgfqrfwpvf             ";
            LETTER1 = LETTER1 + "                                                  aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaagaaaaaaa aaaaaaaaaaaarvhhhhhhhhkuhghhahhihqrkkearcdsddifrwuifsuiyyftpdrkmifriieyowtifiriixasiibydtaeuusjkqrjkkwfkniungifltntertvhkmqmdko                                                               jjjjjjjjjjxjjjjjyjjfjjjjjjjjjjjwjjjjjjjjjjjjsjjjjfjjjjfejfjjwjj jjjjjjjjjdjajjjjjjjjjjjjjjjjjjtjjitwyyrtcsshmqmusrtxuwruthtpltwinfkqilrtejpvggnrreqbccserkrkjivgpgqgyigfvopdrjrnpvdeigysmtjyyyd                                                               fjajjsjjjfjjjjejjjjajjjjjgjjjgjjjjjjjjjqfjjjjjjjjjjjnjjjjjjyjjt jjjjjujjjjjjtjjfjffjjjscjffjjyoeymtqffslknyixaatwwnxfakllktwiynnbuijyuxktyukwwrjiptfariakqqiynfasgkxggrtrwwfdfjtqtnyaassddjkkqt                                                               jjfjjjjnjbaywfjjjnnjjfjajjjjjjjjjjgjjfjjujjjjjjjdjjjjjjjjfajjfg fjajljxjjjajhjjjjjjjjfjjjjasjtjdjttqteqnooiinsdynvfqitbcxhjafljmwqgddkrqtwqxdjttuixvjbgfeequpbbxsdqttyixupyskyaaswtqadfikkqi";
            LETTER1 = LETTER1 + "pij                                                               ubjfjjuejtjyjjjjjfjjgxijaytttttttvttttttttttttttttppppppppppppy pppappppypppppppppppppdpyppppppppifsiktushjjafrraweypsrqniiynaaqruunnwtjeqniggggtsfsnvkqeqidcwwuskqtpxfdfhketyaswvyynvvxxlkpeyy                                                               yppxyppppppppppppppppqpppyppppprypnpvpypppppppppyppphrppjpppppp ppppyyppppppeppppypppbptpyopypppptuhxaaipftkttqyvcvgiyybndralkuaajmtiakgygkuoifgdjmtyuuoidrhtidfadddkuopycgmmtsrwuuibrwuusirevg                                                               ppfypnppppyppppppppppppppppppppppppppppppppppppppppppuppppppppp pgssssssssmcimfmttegnpnhqirifmfvgraepyvkeasiskbwjubdrokjeyigfarqwwyagktwexipvxsjwnncnarjkmwteqxuyyuunyuiyyyynnnxaalrubvkqipqvxb                                                               othmwakfuumpofhlatwuehumghgapfammqqrqqqqqquqdqqqqqqqqqdqqqqwqqx qqqqqyyyvyyyyyyyyyyyyyymyyyyyuyyyqasmyyxaaaajqyejxdjkrweuyykjkiiyccexwwndmmqqiiseddwtycxgiggshjwwwwqniibcvfg";
            LETTER1 = LETTER1 + "mtpyngfadkjkmtwwqyi                                                               yyyyyyyyyyyyyyyyyyyyyyyyyytyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy dyyyyyyywyyyyyyyyyyyyyyyyyyyyyyyyippcccqipfffdrllklqixfadqbjxfkqrtenudfkqbcfasjueadvffppfgdkrltmeagooagjickktroogrmimtfnumrkisl                                                               yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhyyyy yyayyyyyyyyyywyyyyyyyyyyyyyyyyyyyquhssktoyryppwphtqoigllmnashhuixsuuixiisdmmweubrjrifjliyvyrrrlfqayigafsdghqwsuyfrqbarhtqqngrgg                                                               yyyyyyyytyyyyyyyyyyyyyyyyyyyyyyyeyyjyyyyoyyyyyyyyyyyyyyyyyyyyyy yyyyayyyyyyyyyyyyyfyyfyyxyyyyyyyymuuyasfkjteeipxbfsgrwwfrhkkxxfrrgglmmrtttrquiipkkkqyxtetwwtmyiyxlevkqpncgsjrqyyetofrhkyasejmqt                                                               yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyykyyyyyyyyyuyyyyyyyyyhawyyyyyyyyt yyyxuyywtwyyyyyyyyyyyyyyyyyyyyyyywipcrrrfdlrmtsyuuruusqwgbxyurrhhgaskuoiuuuuiibhwoibtipdskpx";
            LETTER1 = LETTER1 + "uxqfdrtkyypybxqtksjluujdwswwwy                                                                    twwwwwwewwwwwmmwgagbmbbbggguggggggggghgggegggfggggggeeeeeeeeeee eeeeeeeeeeeeeeeemfcqmaammmwwmwxgrfgggagggbggghjtxttqrqttvttiybenhfgffdddddddddaaaaaafhjqqcdmmgdopasdwatmmwwwwwwwwwwwwwwwwwwwwww                                                               fhamhgkcmlwmmxmmmqlfmwmmmusmhmyhmhmhmppmmmhhsfmmihmyafmmmmpmrfh mvmmhwhgmmfemhmmpamajmmfgmyhmtdmmwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwttwniuuuqqqqqmmyuyuyyyyyyyyuuuu                                                               mymuahlqmdmhmuhcmmmyfffffffffffffffffffffffffffffffffffffffffff fffffffffffffffkkkkkkkkkkkkkkkkkkupppyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyybbbbbbbbbbbbbbbbbbbbbfayyqygguo                                                               kkkkkkkkkkkkkkkkkkkwkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk kkkkkkkkkklkkkkkkkkkkkkkkkkkkkkkkqcggrwqqpgktqeroasgautubfdqqdqvylbjlvohpbiq";
            LETTER1 = LETTER1 + "ccccwgwygyhffffffffffffffffffffffffffffffffffffffff                                                               kydkkkkkkkkknkkakkkkkkkkkktkkktkkakkkkkkkkkkttttttttttttttttttt tttttttlllpllllllllllllllllllllglffffffffffffffffffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa                                                               lllllllclllulllllllllllllllllallllllflmlllllllllllllllllillllll llflldlslllllllllllllllllllwllfllaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa                                                               llllllllllllllllllllllllwlglxllllllllctugebuuhueuumskegevftmffb ntgegdydgkhnajyqpflmdspggqfthsrgcaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaydddyendddddrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr                                                               yglilwsdaccrmwyhjffajdunujhypkmfnfqvblrnfucxuucgghtknafsnckkdta lywfttttqlgsnmfvqfywrpfgodqnglffdrrrrrrrrrrrrraaaqkkkkkkkkkk";
            LETTER1 = LETTER1 + "kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkqqqtqvttlqqvyuuxntipkquwtxtcdntqiamnuwnqadrqclundtojqqqqpdpcnitywfrttftytdgkggyggfwmqggmbusvtuxhqhnnafwtpwwxxvyptdygqtwxkyyaeyqngfqjqtwkvqueuqouhokwmayffydaaqtakkukkkkkkkkkkkkkkkkukkikkkikkkkkkkkqkkkspkkkkxkdkkkvkkkkkkkkkkkkskkkkkkkkqkklllllllllllmmmvmmmoqjjjgddbggpbqfyjdhshhbsjqghfqqqqsqpesqqccbqhtvjqgrhgtcktgqphtqmtgswsssssssssssfssssssssssssssssstssssslssotsusjsssdussssssssyqssssswsssspttfqqqqqqqqqcqqgqwqqqqmmmmmmmmmmmmmgnmymmmmmwmmmmmmmmmmmmmmmmmmmmmmmgmmmmmmmmmummutltttttfttttteqqrqqqqqqqqqqqbqqqqqqqaqfadmqnbsdmqvqshqcdxfuhklgqqfutcevqqvqmqqqfqqrftdkqqgubsashqqqqqqqqqqqqqqqqgqqqqqqqqqqqququqqquqqqqqqqqcwqmqqqqqqqqqqoqqqqqcqqqqqqqqhqqqqqqqkqqxqqqqqqcqqqqqqqqqqqqbqqnqqqqqqqqqqqqjqqtqqqqqqqqqgqqqqqqqqqqyyyyyyysyqyqyyyyyncvnnnndnndtncnninnnnnnunnnngnnqstbqwvfqtyoqiqidmqqqfagummgrfgkgtkfgggexxplfqdjsxjqqmqnjdtqqoeqqqqqbqmqcqqqqqqqqiqqqmqqqqusqqqqqqqdqqqqqqqquqqqqrfqjqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqnnannnnnnnn";
            LETTER1 = LETTER1 + "ndjnsnqnnmnnnqnnnnnftnngbuuuuuuuuuuuuuuuuquuuuuuunniiiseiiiuiqtiiiibiiiiiqiiiiiiiiieqsjqqqesqccqfjftqtjoqfuuuwcqqwbcfifqxyyjijrjijqjqfjhwqujgwgquahjqqqqqqffqrqqqaqnqquqqqqqqqqfuqquqomqqqriqqqqqqwqqqqqqqqqfqqqqdqqtrqqyqqyqqqqqquqaqcqqqqqiqtqqqqqiiiiiiiiiiiiiiqiiiiiiiituiiqiiiiqiiigjgiyiiiiiiiiiiiiiiiiiiiiiiiiquiqiiigiiiqtifiiiiibiiiiiqityqqyktkgsuaiqqfitwwjqfyqvmbvkfqtqdhqnycqvfqqqclgutlpkqqyddqjqgqqgqqqqquqqqgqaqqfqqyqqqqqqqqtqhqqqqppqqqqquhwqqeqqqqaqqaqqqqqdaqdixqqqjqqqqqqqwqrqqqqsqbqxqqvqqtiifiiiimqiciiisgqpmxppyppppppvayeatmttgfggqtcgfiqcftmvasunqyjqjohqepvcqxxnnscmnnvvvxthxhvtvvvqmhsqqqkququwwuubgsqcnqsdqknqqodwqptqyqyybqqcqcveququqqqumqwawdhqqqquqqqtqqqgqqqqtqqqqqqrcqqcpqqqqaqqqqqqqqqqmqtqxqiqqovwqhqqqqftqqqqqqqqdjqsqqqqpqqqqqqqqnqqqqqqdvqvvvcvvuvvvyuvtvvvviqvsltqjcuvqvvcyvvtvbfvvvqvvvvqlvvdqlvuoooccxccvccqctcxccbcqccqqcscxxxdxojlkfqtfusdgsyfqfpqejdqqgpgsqskrrxdqmmdqdfmggkddqoblhyqcyqsoeukswqqxqqqqfqfqqqqqfhqhqqqbflymqqqqqiqqmqcmqqqqqqqqmgqsqeubuqqqqquubqjqamqqseqhqqaqqqqqsqqqqqqq";
            LETTER1 = LETTER1 + "blgqqxxxqxcxtsuckctxxqxyxyxxqxxxexxxyxqyxxtxxtqxcqxxuxxxlxfxxaxxqdvvjogdgcjtyjggdcaggggsqqngggprgrguuoijfedqtafqaatjjqpffpyoyydgoexpkheqdggggaaqshintjqqnunhuttjkhqqqqqmqyqteauqqqeqqhqcqtqfflqheqqqsqaqejdqqtqqjgquuqqqqqqyhytbjhqqqrqqfqqeqqbqkoqbqqpqqqvqdqqqqqaaahgggkjgpugpfgggdgqmgwjffsbsqycsussdjduqcdsqssqusjsssssseuausnnnssssmsscqycjmsrushsrtsshhstlsqqrqtchihtbcqqtqksfkrgfrpjrrrajyqccqqdqydcrqyyudtamgtqyqpddaqhtqqcqeqqjqqqsupodkumasauubyuadtuqqwcuuuwawuuqujuqulafugffaaptajutqaauutuujufjqtuuuobuuccguuufluuquqdqvhujhshsfcclqtjuqdquslssusssdptuqssstlpwsqnqsbgcejcsskscsbnquvpfgggejhtqgxaueblllqcllldclelmccqquyqftmdquiqiiqtfqtkeqbujqcqqqqogttjmdqwncycqqtqqqtaqedbbbtvqqtunungqqqqwouqvvuecpatuuuqfqhumbbbbbbqlqesbbwccdfcbkdqxjmbmcxbpqbdqcbbucbqmbjqmcbbbbvbqbbbvbhaklmoggwihudqkqqdqaacukqmqeqjsjjjhqtqjqafbjjjqqqyjkanjjjjqcgqmrhuemcfqrusqajwucqjummptddgagllxfqdpthjwdqwhqpbqircqglajfvqttdqqqmgftvstcqpanqqgqlbtttrmocleqqqfqqcbcbbscddbbqvckckebbyeanubbebroawanqffomvwutqiqqjyvqbqfqwwqqqfcqyyvfwftedh";
            LETTER1 = LETTER1 + "hdqgfgaftfffuacfftftfcpqqowtsjqqwfurjqrrvrfqncctepevplqufmedqlcprpokmewetequueuuujekejajqsfeyeexquuuxxqqejqkteeimmtctawhahhtkuqtactcqcqdweddqwqmthdnegrrcdosjqoxquoqdqamaiirwqqpcscqfqdajghhfudfltyufaylddqalhullwvdvhdodsddhgdccjdcacamdmojumqsucutaqqeaeaapxchkeaeqdoqqqyaopdalaahsghqahwqtqttymhnumujyoqyulaquqqvtjougcfuhcqcfohfhhsjqwunmomuaohyhhxxuxqqyqypjqcpqpupqqcjpqqljvuvtvfqmpjqqmqcqqqhuphyhvqqcwcjgtpprcwqcqcwssaqptaqqpfifqjfcekdqlqwwvtchhqnnuquotflqmcttthhlqqqlqqttdququujyhuqyqqciqymmlcqjcqyqctqrdqfpyytqltcdlpplqqtdgcfxtrkckoseruutqkctbqffftqttvktctcddsctcqcqrrqttukqyuqctfcydmmqqwctqpqhtuhfqhfdqeeqvyqhtdthhcccdgqqoqqychqqkpqquq";


            char[] c = thisletter.ToCharArray();
            for (int i = 0; i < c.Length; i++)
            {

                byte[] sarr = System.Text.Encoding.Default.GetBytes(c[i].ToString());
                if ((int)sarr[0] > 128)
                {
                    int QW = 254 * ((int)sarr[0] - 129) + (int)sarr[1] - 64 + 1;
                    if (QW < 1)
                    {
                        pystring += "?";
                    }
                    else
                    {
                        if (QW > LETTER1.Length)
                        {
                            pystring += "?";
                        }
                        else
                        {
                            pystring += LETTER1.Substring(QW - 1, 1);
                        }
                    }
                }
                else
                {
                    pystring += c[i].ToString();
                }
            }
            pystring = pystring.Replace(" ", "");
            return pystring;
        }

        /// <summary>
        /// 返回拼音码
        /// </summary>
        /// <param name="hzStr">汉字字符串</param>
        /// <returns></returns>
        public static string GetPYCode(string hzStr)
        {
            hzStr = hzStr.Replace(" ", "").Trim();
            StringBuilder result = new StringBuilder();
            string str = "";
            for (int i = 0; i < hzStr.Length; i++)
            {
                str = hzStr[i].ToString();
                if (!char.IsPunctuation(hzStr[i]))
                {
                    if (str.CompareTo("吖") < 0) { }
                    else if (str.CompareTo("驁") <= 0) str = "a";
                    else if (str.CompareTo("簿") <= 0) str = "b";
                    else if (str.CompareTo("錯") <= 0) str = "c";
                    else if (str.CompareTo("鵽") <= 0) str = "d";
                    else if (str.CompareTo("樲") <= 0) str = "e";
                    else if (str.CompareTo("鰒") <= 0) str = "f";
                    else if (str.CompareTo("腂") <= 0) str = "g";
                    else if (str.CompareTo("夻") <= 0) str = "h";
                    else if (str.CompareTo("攈") <= 0) str = "j";
                    else if (str.CompareTo("穒") <= 0) str = "k";
                    else if (str.CompareTo("鱳") <= 0) str = "l";
                    else if (str.CompareTo("旀") <= 0) str = "m";
                    else if (str.CompareTo("桛") <= 0) str = "n";
                    else if (str.CompareTo("漚") <= 0) str = "o";
                    else if (str.CompareTo("曝") <= 0) str = "p";
                    else if (str.CompareTo("囕") <= 0) str = "q";
                    else if (str.CompareTo("鶸") <= 0) str = "r";
                    else if (str.CompareTo("蜶") <= 0) str = "s";
                    else if (str.CompareTo("籜") <= 0) str = "t";
                    else if (str.CompareTo("鶩") <= 0) str = "w";
                    else if (str.CompareTo("鑂") <= 0) str = "x";
                    else if (str.CompareTo("韻") <= 0) str = "y";
                    else if (str.CompareTo("咗") <= 0) str = "z";
                    result.Append(str);
                }
                else
                    str = "";
            }
            return result.ToString();
        }
    }
}
